pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }

    buildscript {
        repositories {
            mavenCentral()
        }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "GitHubSearchMVVM"

include ':core'
include ':core:ui:compose'
include ':core:ui:view'

include ':networking'
include ':app'
include ':search'
include ':navigation'
